# Generated by Django 3.0.5 on 2021-04-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=122)),
                ('card_num', models.CharField(max_length=20)),
                ('exp_year', models.CharField(max_length=5)),
                ('exp_month', models.CharField(max_length=3)),
                ('cvv', models.CharField(max_length=4)),
            ],
        ),
    ]
