# Generated by Django 3.0.5 on 2021-04-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=122)),
                ('validity', models.CharField(max_length=122)),
                ('speed', models.CharField(max_length=122)),
                ('data', models.CharField(max_length=100)),
                ('subsc', models.TextField()),
            ],
        ),
    ]
