# Generated by Django 3.0.5 on 2021-04-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accno', models.CharField(max_length=122)),
                ('regno', models.CharField(max_length=122)),
            ],
        ),
    ]
